# .github/workflows/epub-a11y-explain.yml
name: CI (EPUB Accessibility 1.2 Explainer)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "epub34/a11y-explain/**"
      - "common/**"
  push:
    branches: [main]
    paths:
      - "epub34/a11y-explain/**"
      - "common/**"
jobs:
  main:
    name: Publish EPUB Accessibility 1.2 Explainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub34/a11y-explain/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_A11Y_EXPLAIN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-pm-wg/2023Oct/0028.html
          W3C_BUILD_OVERRIDE: |
             shortName: epub-a11y-explain-12
             specStatus: DNOTE
