# .github/workflows/epub-rs-33.yml
name: CI (Reading System)
on:
  pull_request:
    paths: 
      - "epub33/rs/**"
      - "epub33/common/**"
  push:
    branches: [main]
    paths: 
      - "epub33/rs/**"
      - "epub33/common/**"
jobs:
  main:
    name: Publish Reading Systems 3.3 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub33/rs/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_RS }}
          W3C_WG_DECISION_URL: https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2
          W3C_BUILD_OVERRIDE: |
             shortName: epub-rs-33
             specStatus: WD
