# .github/workflows/epub-overview-34.yml
name: CI (Overview)
on:
  pull_request:
    paths: 
      - "epub34/overview/**"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "epub34/overview/**"
      - "common/**"
jobs:
  main:
    name: Publish EPUB 3 Overview 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub34/overview/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_OVERVIEW }}
          W3C_WG_DECISION_URL: https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2
          W3C_BUILD_OVERRIDE: |
             shortName: epub-overview-34
             specStatus: NOTE
